# Site settings
title: Lisa for Springfield
email: jonathonarnold@me.com
url: https://www.lisaforspringfield.com
description: "Prouldy Serving as Alderman for Ward Five of Springfield, Tennessee"
keywords: ""
skills: "Prouldy Serving as Alderman for Ward Five of Springfield, Tennessee"
meta_author: Lisa Arnold

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1b365d 
  primary-rgb: "27,54,93" 
  secondary: 780000 
  secondary-dark: 450000

# Footer settings
footer:
  copyright: Lisa Arnold
  location: Lisa Arnold
  social: Get in Touch
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/lmdivirgilio
  - title: instagram
    url: https://www.instagram.com/lis.arnold/
  - title: linkedin
    url: https://www.linkedin.com/in/lisadivirgilio/


# Postal address (add as many lines as necessary)
address:
  - line: 101 5th Avenue, Second Floor
  - line: Springfield, TN 37172

# Credits content
credits: 'Lisa Arnold bio blurb goes here'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
